import Link from "next/link";
import { redirect } from "next/navigation";
import { isOrganizationAccessError, requireOrganizationContext } from "../../lib/auth/organization-context";
import { listConnectionRequests, listConnections } from "../../lib/connections/service";

export const dynamic = "force-dynamic";

export default async function ConnectionsPage() {
  let context;
  try { context = await requireOrganizationContext(); } catch (error) { if (isOrganizationAccessError(error)) { if (error.code === "AUTHENTICATION_REQUIRED") redirect("/auth"); if (error.code === "ORGANIZATION_SELECTION_REQUIRED") redirect("/organizations/select"); redirect("/access-pending"); } throw error; }
  const [connections, requests] = await Promise.all([listConnections(context), listConnectionRequests(context)]);
  return <main className="workspace-shell"><header className="workspace-header"><div><span className="eyebrow">Account Connections</span><h1>Your connected systems</h1><p className="workspace-muted">Inventory and authorize the read-only systems your marketing workspace needs. MioDio never asks for platform passwords or platform MFA codes.</p></div><div className="workspace-header-actions"><Link className="secondary-button" href="/dashboard">Dashboard</Link><Link className="secondary-button" href="/connections/manual">Track invitation/export</Link><Link className="primary-button" href="/connections/setup">Add system →</Link></div></header><section className="workspace-grid"><article className="workspace-card workspace-card-wide"><div className="workspace-card-heading"><div><span className="eyebrow">Tracked connections</span><h2>{connections.length ? `${connections.length} systems` : "No connections yet"}</h2></div><span className="workspace-count">Read-only first</span></div>{connections.length ? <div className="connection-summary-list">{connections.map((connection) => <Link className="connection-summary-row" href={`/connections/${connection.id}`} key={connection.id}><span><strong>{connection.provider}{connection.product ? ` · ${connection.product}` : ""}</strong><small>{connection.resources.filter((resource) => resource.selected).length} selected · {connection.healthChecks[0]?.outcomeCode ?? "not verified"}</small></span><span className={`status-pill status-${connection.status}`}>{connection.status.replaceAll("_", " ")}</span></Link>)}</div> : <div className="workspace-empty"><p>Start with a non-secret inventory. You can record systems that need an invitation or approved export even when a provider API is not ready.</p><Link className="primary-button" href="/connections/setup">Create an account request →</Link></div>}</article><article className="workspace-card workspace-card-wide"><div className="workspace-card-heading"><div><span className="eyebrow">Inventory requests</span><h2>{requests.length ? `${requests.length} requests` : "No inventory requests"}</h2></div></div>{requests.length ? <div className="connection-summary-list">{requests.map((request) => <Link className="connection-summary-row" href={`/connections/setup?request=${request.id}`} key={request.id}><span><strong>{request.provider}{request.product ? ` · ${request.product}` : ""}</strong><small>{request.system.replaceAll("_", " ")} · {request.ownershipStatus.replaceAll("_", " ")}</small></span><span className="status-pill">{request.state.replaceAll("_", " ")}</span></Link>)}</div> : <p>Requests you save for later will appear here.</p>}</article></section><footer className="workspace-footer"><Link href="/dashboard">← Back to dashboard</Link><span>Use provider authorization or an official invitation. Never email credentials.</span></footer></main>;
}
